### ISSUE TITLE
Problem  with project installation

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/react-ocl-nmr#14]
I guess than my configuration define @zakodium as being from github and we should republish eslint-config ?

npm ERR! 404 Not Found - GET https://npm.pkg.github.com/@zakodium%2feslint-config - npm package "eslint-config" does not exist under owner "zakodium"

Or should we move this configuration to zakodium-oss ?

@targos Could you help me with this ?

**Comment by targos** [comment]
`@zakodium/eslint-config` should not be used anymore. It was replaced by `eslint-config-zakodium`
